name: Build and publish tagged docker image

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone this repository
      uses: actions/checkout@v2
      with:
        path: app
    - name: Parse the tag
      id: tag_parsing
      run: |
          export VERSION=${GITHUB_REF/refs\/tags\//}
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
    - name: Build and run
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" > ~/GH_TOKEN.txt
        cat ~/GH_TOKEN.txt | docker login -u rfns --password-stdin ghcr.io
        docker build -t ghcr.io/rfns/iris-ci/iris-ci:${{ steps.tag_parsing.outputs.VERSION }} app
        docker push ghcr.io/rfns/iris-ci/iris-ci:${{ steps.tag_parsing.outputs.VERSION }}

