name: Build and publish tagged docker image

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone this repository
      uses: actions/checkout@v2
      with:
        path: app
    - name: Parse the tag
      id: tag_parsing
      run:  echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Build and run
      run: |
        echo "${{ secrets.GH_TOKEN }}" | docker login -u rfns --password-stdin docker.pkg.github.com
        docker build -t docker.pkg.github.com/rfns/test-runner/port-test-runner:${{ steps.tag_parsing.outputs.VERSION }} app
        docker push docker.pkg.github.com/rfns/test-runner/port-test-runner:${{ steps.tag_parsing.outputs.VERSION }}


